import { describe, expect, it } from "vitest";
import { parseSource } from "../../ast/parser";
import { analyzePerformanceCosts, cachePerformanceRules, PerformanceAnalysisEngine, PerformanceRuleRegistry, resiliencePerformanceRules, type PerformanceRule } from "..";

function findings(source: string, rules: readonly PerformanceRule[]): readonly string[] { const registry = new PerformanceRuleRegistry(); rules.forEach((rule) => registry.register(rule)); return new PerformanceAnalysisEngine().analyze({ file: "feature.ts", source, ast: parseSource(source) }, registry).map((item) => item.ruleId); }

describe("wave 5 performance rules", () => {
  it("detects unbounded cache growth and missing freshness", () => { const ids = findings('const balanceCache = new Map(); balanceCache.set(accountId, balance);', cachePerformanceRules); expect(ids).toContain("performance.cache.unbounded"); expect(ids).toContain("performance.cache.missing-ttl"); expect(ids).toContain("performance.cache.critical-data-without-freshness-policy"); });
  it("recognizes cache eviction and ttl evidence", () => { const ids = findings('const cache = new Map(); const ttl = 1000; cache.set(id, value); cache.delete(id);', cachePerformanceRules); expect(ids).not.toContain("performance.cache.unbounded"); expect(ids).not.toContain("performance.cache.missing-ttl"); });
  it("detects cache miss recomputation and stampede risk", () => { const ids = findings('const cache = new Map(); async function load(id) { const cached = cache.get(id); if (!cached) { const value = await fetch(`/x/${id}`); cache.set(id, value); return value; } return cached; }', cachePerformanceRules); expect(ids).toContain("performance.cache.stampede-risk"); expect(ids).toContain("performance.cache.recompute-on-miss"); });
  it("checks fetch timeout and retry semantics", () => { const ids = findings('while (true) { await fetch(url, { method: "POST" }); }', resiliencePerformanceRules); expect(ids).toContain("performance.resilience.missing-timeout"); expect(ids).toContain("performance.resilience.unbounded-retry"); expect(ids).toContain("performance.resilience.retry-without-backoff"); expect(ids).toContain("performance.resilience.retry-non-idempotent"); });
  it("accepts abort timeout and jittered backoff", () => { const ids = findings('for (let attempt = 0; attempt < 3; attempt++) { await fetch(url, { signal: AbortSignal.timeout(1000) }); await sleep(100 * 2 ** attempt + Math.random() * 50); }', resiliencePerformanceRules); expect(ids).not.toContain("performance.resilience.missing-timeout"); expect(ids).not.toContain("performance.resilience.retry-without-backoff"); expect(ids).not.toContain("performance.resilience.retry-without-jitter"); });
  it("builds stable symbolic cost summaries", () => { const source = 'for (const id of ids) { await fetch(`/x/${id}`); JSON.stringify(id); }'; const context = { file: "feature.ts", source, ast: parseSource(source) }; const first = analyzePerformanceCosts(context); const second = analyzePerformanceCosts(context); expect(first).toEqual(second); expect(first.operations.map((operation) => operation.kind)).toEqual(["network", "serialization"]); expect(first.operations[0]?.kinds).toEqual(["network", "external-service"]); expect(first.operations.every((operation) => operation.repeated)).toBe(true); expect(first.paths.some((step) => step.label === "repeated in loop")).toBe(true); });
});
