import type { TSESTree } from "@typescript-eslint/typescript-estree";
import { createPerformanceFindingId } from "../engine/finding-id";
import type { PerformanceFinding, PerformanceRule, PerformanceRuleContext } from "../model/types";

export function visit(node: TSESTree.Node, callback: (node: TSESTree.Node, ancestors: readonly TSESTree.Node[]) => void, ancestors: readonly TSESTree.Node[] = []): void { callback(node, ancestors); for (const value of Object.values(node)) { if (isNode(value)) visit(value, callback, [...ancestors, node]); else if (Array.isArray(value)) for (const item of value) if (isNode(item)) visit(item, callback, [...ancestors, node]); } }
export function isNode(value: unknown): value is TSESTree.Node { return typeof value === "object" && value !== null && "type" in value && typeof value.type === "string"; }
export function callName(node: TSESTree.CallExpression): string | undefined { if (node.callee.type === "Identifier") return node.callee.name; if (node.callee.type === "MemberExpression" && !node.callee.computed && node.callee.property.type === "Identifier") return node.callee.property.name; return undefined; }
export function isLoop(node: TSESTree.Node): boolean { return node.type === "ForStatement" || node.type === "ForInStatement" || node.type === "ForOfStatement" || node.type === "WhileStatement" || node.type === "DoWhileStatement"; }
export function finding(rule: PerformanceRule, context: PerformanceRuleContext, node: TSESTree.Node, message: string, suggestion: string): PerformanceFinding { const range = node.range === undefined ? undefined : { start: node.range[0], end: node.range[1] }; const location = { path: context.file, line: node.loc?.start.line, column: node.loc?.start.column, range }; return { id: createPerformanceFindingId({ ruleId: rule.meta.id, path: context.file, range }), ruleId: rule.meta.id, title: rule.meta.title, message, severity: rule.meta.defaultSeverity, confidence: rule.meta.defaultConfidence, category: rule.meta.category, location, evidence: [{ message, location }], suggestion }; }
