import type { TSESTree } from "@typescript-eslint/typescript-estree";
import type { PerformanceFinding, PerformanceRule } from "../model/types";
import { callName, finding, isLoop, visit } from "./ast-utils";

const definitions = [
  ["performance.backpressure.unbounded-queue", "Unbounded queue growth", "A queue-like collection is appended from a repeated producer without local drain evidence.", "Bound the queue, batch work, or add a drain/pause mechanism."],
  ["performance.backpressure.missing-concurrency-limit", "Unbounded concurrent fan-out", "Promise.all fans out work from a dynamic collection without limiter evidence.", "Use a configured concurrency limiter or bounded batches."],
  ["performance.rate-control.hot-loop-external-call", "External call in hot loop", "A known external request is issued for every loop iteration.", "Batch, cache, or rate-limit requests before issuing them in a loop."],
] as const;
const EXTERNAL_CALLS = new Set(["fetch", "request", "send"]);
export const backpressurePerformanceRules: readonly PerformanceRule[] = definitions.map(([id, title, message, suggestion]) => ({ meta: { id, title, description: message, category: id.startsWith("performance.rate-control") ? "rate-control" : "backpressure", defaultSeverity: "high", defaultConfidence: "high" }, check(context) { const findings: PerformanceFinding[] = []; const drainedQueues = collectDrainedQueues(context.ast); visit(context.ast, (node, ancestors) => { if (id === "performance.backpressure.unbounded-queue" && node.type === "CallExpression" && callName(node) === "push" && queueName(node) !== undefined && ancestors.some(isLoop) && !drainedQueues.has(queueName(node) ?? "")) findings.push(finding(this, context, node, message, suggestion)); if (id === "performance.backpressure.missing-concurrency-limit" && isDynamicPromiseAll(node)) findings.push(finding(this, context, node, message, suggestion)); if (id === "performance.rate-control.hot-loop-external-call" && node.type === "CallExpression" && EXTERNAL_CALLS.has(callName(node) ?? "") && ancestors.some(isLoop)) findings.push(finding(this, context, node, message, suggestion)); }); return findings; } }));
function isDynamicPromiseAll(node: TSESTree.Node): boolean { return node.type === "CallExpression" && node.callee.type === "MemberExpression" && !node.callee.computed && node.callee.object.type === "Identifier" && node.callee.object.name === "Promise" && node.callee.property.type === "Identifier" && node.callee.property.name === "all" && node.arguments[0]?.type === "CallExpression" && callName(node.arguments[0]) === "map"; }
function queueName(node: TSESTree.CallExpression): string | undefined { return node.callee.type === "MemberExpression" && node.callee.object.type === "Identifier" ? node.callee.object.name : undefined; }
function collectDrainedQueues(ast: TSESTree.Program): ReadonlySet<string> { const drained = new Set<string>(); visit(ast, (node) => { if (node.type === "CallExpression" && ["shift", "splice", "pop"].includes(callName(node) ?? "")) { const name = queueName(node); if (name) drained.add(name); } }); return drained; }
