import type { TSESTree } from "@typescript-eslint/typescript-estree";
import type { PerformanceFinding, PerformanceRule } from "../model/types";
import { callName, finding, isLoop, visit } from "./ast-utils";
const definitions = [["performance.network-waterfall", "Network waterfall", "Independent literal network requests are awaited sequentially.", "Start independent requests before awaiting their combined result."], ["performance.network.sequential-independent-requests", "Sequential independent requests", "Two literal requests have no data dependency evidence but are awaited in sequence.", "Use Promise.all when both requests are safe to run concurrently."], ["performance.network.duplicate-request", "Duplicate network request", "The same literal request is issued more than once in the same file.", "Coalesce or cache the request result where response semantics allow it."], ["performance.network.request-in-loop", "Network request in loop", "A request is issued per loop iteration.", "Batch the request or use bounded concurrency."], ["performance.network.excessive-roundtrips", "Excessive network roundtrips", "A function contains three or more direct network requests.", "Aggregate data behind a purpose-built endpoint where practical."]] as const;
export const networkPerformanceRules: readonly PerformanceRule[] = definitions.map(([id, title, message, suggestion]) => ({ meta: { id, title, description: message, category: "network", defaultSeverity: "medium", defaultConfidence: "high" }, check(context) { const findings: PerformanceFinding[] = []; const requests = collectRequests(context.ast); const awaitedLiteralRequests = requests.filter((request) => literalUrl(request) !== undefined && hasAwait(request, context.ast)); visit(context.ast, (node, ancestors) => { if (node.type !== "CallExpression" || !isRequest(node)) return; if (id === "performance.network.request-in-loop" && ancestors.some(isLoop)) findings.push(finding(this, context, node, message, suggestion)); if (id === "performance.network.duplicate-request" && literalUrl(node) !== undefined && requests.filter((candidate) => literalUrl(candidate) === literalUrl(node)).length > 1) findings.push(finding(this, context, node, message, suggestion)); if (id === "performance.network.excessive-roundtrips" && requests.length >= 3) findings.push(finding(this, context, node, message, suggestion)); if ((id === "performance.network-waterfall" || id === "performance.network.sequential-independent-requests") && literalUrl(node) !== undefined && awaitedLiteralRequests.length >= 2 && ancestors.some((ancestor) => ancestor.type === "AwaitExpression")) findings.push(finding(this, context, node, message, suggestion)); }); return unique(findings); } }));
function isRequest(node: TSESTree.CallExpression): boolean { return ["fetch", "request"].includes(callName(node) ?? ""); }
function literalUrl(node: TSESTree.CallExpression): string | undefined { const argument = node.arguments[0]; return argument?.type === "Literal" && typeof argument.value === "string" ? argument.value : undefined; }
function collectRequests(ast: TSESTree.Program): readonly TSESTree.CallExpression[] { const result: TSESTree.CallExpression[] = []; visit(ast, (node) => { if (node.type === "CallExpression" && isRequest(node)) result.push(node); }); return result; }
function hasAwait(target: TSESTree.Node, ast: TSESTree.Program): boolean { let result = false; visit(ast, (node, ancestors) => { if (node === target && ancestors.some((ancestor) => ancestor.type === "AwaitExpression")) result = true; }); return result; }
function unique(findings: readonly PerformanceFinding[]): readonly PerformanceFinding[] { return [...new Map(findings.map((finding) => [finding.id, finding])).values()]; }
