import type { PerformanceConfidence, PerformanceFinding, PerformanceProfile, PerformanceSeverity } from "../model/types";

export type PerformanceProfileId = "performance/default" | "performance/strict" | "performance/financial" | "performance/banking";
export interface ResolvedPerformanceProfile { readonly id: PerformanceProfileId; readonly enabledRuleIds: readonly string[]; readonly disabledRuleIds: readonly string[]; readonly severityOverrides: Readonly<Record<string, PerformanceSeverity>>; readonly minimumConfidence?: PerformanceConfidence; readonly criticalEntrypoints: readonly string[]; }
export const PERFORMANCE_PROFILE_DEFINITIONS: Readonly<Record<PerformanceProfileId, PerformanceProfile>> = {
  "performance/default": { id: "performance/default" },
  "performance/strict": { id: "performance/strict", extends: "performance/default", minimumConfidence: "medium" },
  "performance/financial": { id: "performance/financial", extends: "performance/strict", severityOverrides: { "performance.database.query-in-loop": "high", "performance.resilience.missing-timeout": "high" } },
  "performance/banking": { id: "performance/banking", extends: "performance/financial", severityOverrides: { "performance.transaction.external-call-in-critical-section": "critical", "performance.transaction.unbounded-fanout": "critical", "performance.bank-ui.blocking-critical-render": "high" } },
};
export function resolvePerformanceProfile(id: PerformanceProfileId, definitions: Readonly<Record<string, PerformanceProfile>> = PERFORMANCE_PROFILE_DEFINITIONS): ResolvedPerformanceProfile { const visited = new Set<string>(); const resolve = (current: string): ResolvedPerformanceProfile => { if (visited.has(current)) throw new Error(`Performance profile inheritance cycle at "${current}".`); const profile = definitions[current]; if (!profile) throw new Error(`Unknown performance profile "${current}".`); visited.add(current); const parent = profile.extends ? resolve(profile.extends) : { id: current as PerformanceProfileId, enabledRuleIds: [], disabledRuleIds: [], severityOverrides: {}, criticalEntrypoints: [] }; return { id: id, enabledRuleIds: [...parent.enabledRuleIds, ...(profile.enabledRuleIds ?? [])], disabledRuleIds: [...parent.disabledRuleIds, ...(profile.disabledRuleIds ?? [])], severityOverrides: { ...parent.severityOverrides, ...profile.severityOverrides }, minimumConfidence: profile.minimumConfidence ?? parent.minimumConfidence, criticalEntrypoints: [...parent.criticalEntrypoints, ...(profile.criticalEntrypoints ?? [])] }; }; return resolve(id); }
export function applyPerformanceProfile(findings: readonly PerformanceFinding[], profile: ResolvedPerformanceProfile): readonly PerformanceFinding[] { return findings.filter((finding) => !profile.disabledRuleIds.includes(finding.ruleId) && (profile.enabledRuleIds.length === 0 || profile.enabledRuleIds.includes(finding.ruleId))).filter((finding) => meetsMinimumConfidence(finding.confidence, profile.minimumConfidence)).map((finding) => ({ ...finding, severity: profile.severityOverrides[finding.ruleId] ?? finding.severity })); }
function meetsMinimumConfidence(actual: PerformanceConfidence, minimum: PerformanceConfidence | undefined): boolean { const levels: readonly PerformanceConfidence[] = ["low", "medium", "high"]; return minimum === undefined || levels.indexOf(actual) >= levels.indexOf(minimum); }
